### ISSUE TITLE
Invalid characters in XML attributes values

### ISSUE THREAD

**Issue by leagris** [ATLauncher/Website-Issues#100]
# XML Attributes values with reserved characters must be encoded with numerical entities:
See: [allowed characters in XML attributes](https://www.w3.org/TR/xml/#NT-AttValue)

## Typically
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and MUST, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

## Example
http://download.nodecdn.net/containers/atl/launcher/packs.xml
Line 249 `name="Magic&Technic"` uses invalid character "`&`" and should be changed to `name="Magic&#38;Technic"`

**Comment by RyanTheAllmighty** [comment]
As discussed in Discord, the xml is not used anywhere, this is an old artifact from over a year ago.
