### ISSUE TITLE
[Feature] add Access-Control-Allow-Origin * HTTP header to Node CDN

### ISSUE THREAD

**Issue by leagris** [ATLauncher/Website-Issues#101]
### Feature request:

Would you mind adding an `Access-Control-Allow-Origin *` HTTP header to Node CDN so we can fetch `Configs.xml` or `Configs.json` as well as `packs.json` directly from Node CDN in Browser Javascript `loadXMLDoc` or `XMLHttpRequest` without beying blocked by cross-origin issues?

#### Commented-out fetching from Node CDN because of missing Access Control Header:

https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/blob/master/modlisttransformer.xhtml#L35

#### Work-around by hosting a copy of Configs.xml into github:
https://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlisttransformer.xhtml

### References:
1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by RyanTheAllmighty** [comment]
Giving this to NodeCraft to follow up on.

**Comment by Cherry** [comment]
Thanks. This has been implemented and is now rolling out to all of our CDN nodes. It may take a few minutes to propagate.

Let me know if you have any further issues @leagris!

**Comment by leagris** [comment]
Thank you so much @Cherry @RyanTheAllmighty 
Now it works 😄 ❤️ https://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlisttransformer.xhtml
