### ISSUE TITLE
TrollCraft not a modpack on serverlist

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#102]
You cannot set trollcraft as a modpack on the ATL server listings.

**Comment by RyanTheAllmighty** [comment]
Unfortunately I have no access to a computer at the moment while waiting for a warranty replacement which could take up to 4 weeks.

May get looked into before then if I manage to find some way to come back online.

**Comment by RyanTheAllmighty** [comment]
All fixed
