### ISSUE TITLE
Can't update or create new server listings.

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#103]
Trying to edit or add any servers to the serverlist results in this:
![error](https://i.imgur.com/TtNSWMP.png)

**Comment by RyanTheAllmighty** [comment]
Can you try again and if the error occurs again, note the UTC time and server id trying to edit

**Comment by Time6628** [comment]
1:30 AM UTC. Server id 1363

**Comment by tenten8401** [comment]
Getting this error with my server as well.

**Comment by Yorkforce** [comment]
Same problem, our server listing is gone

**Comment by RyanTheAllmighty** [comment]
Issue has been fixed.

Was due to there being no featured servers.

Shouldn't happen again.

Please let me know on this issue if the issue still occurs for you
