### ISSUE TITLE
skyfactory2 wont boot up HELP PLZZZ

### ISSUE THREAD

**Issue by djhoodie** [ATLauncher/Website-Issues#104]
when i open the at launcher is runs fine but when i go to run sky factory2 is flashes and goes right back to at launcher

http://paste.atlauncher.com/view/1c15efc7

**Comment by djhoodie** [comment]
[crash-2017-12-20_22.34.17-client.txt](https://github.com/ATLauncher/Website-Issues/files/1577845/crash-2017-12-20_22.34.17-client.txt)

**Comment by RyanTheAllmighty** [comment]
This is not for support with packs. If you want support, please visit our discord at https://atl.pw/discord
