### ISSUE TITLE
Select All Tick selects across pages, not just what is shown.

### ISSUE THREAD

**Issue by GodNero** [ATLauncher/Website-Issues#14]
I found this error when trying to clean up some unneeded versions of mods we had in the launcher.

I selected the Select All tick box removed the one mod on the page of 10 items i was looking at, and it deleted all the mods on the subsequent pages after the first.

That gave me quite the scare as some of those mods are still active and being used. You might want to make sure that it ONLY selects from the mods/files shown when ticked. ;)

**Comment by RyanTheAllmighty** [comment]
Alright a warning prompt now shows when using the select all button
