### ISSUE TITLE
Instantly Buying Featured Slots

### ISSUE THREAD

**Issue by rojo8399** [ATLauncher/Website-Issues#15]
Hi, I've been trying to feature my server for the past four weeks now, but there's been a problem almost half the time trying to. When I refresh the page it goes from 1 second to feature my server to 4 days, instantly. People are featuring their server somehow without clicking the "Feature Server" button. This makes it unfair for people who don't know how they do that and they get featured every week non stop. I hope either this issue could be fixed so that you would need to click the button, or something like that. Thanks in advanced. :)

**Comment by RyanTheAllmighty** [comment]
Yeah I shall add in something to force users to actually click on the buttons to stop them from being quickly taken. I imagine they will still be quickly taken, but this way everyone will be forced to do so via the edit page.

**Comment by rojo8399** [comment]
Thank you so much!

**Comment by RyanTheAllmighty** [comment]
All done, now requires captcha field. Will be pushed live within the hour

**Comment by mattymaats** [comment]
I'm still only ever able to get one if I get whoever is buying them instantly by surprise lol.. Ryan are you sure it doesn't work if you just bookmark the paypal link?
