### ISSUE TITLE
Wiki Mod Permissions

### ISSUE THREAD

**Issue by Brodude1234** [ATLauncher/Website-Issues#16]
It says on the wiki that you do not have permission to include Railcraft in a public mod pack. This conflicts with this statement in the official Railcraft wiki:

You are REQUIRED to PUBLICLY post a licensing page with entries for all the mods currently in your mod pack (links to licenses, images of PMs, posts by devs, etc…). This is the single most important requirement you must meet. If you cannot or will not do this, you cannot use Railcraft in your mod pack.

You may not sell the mod pack.

You are not allowed to use the latest series of Railcraft (versioning system being <major.series.revision.build>, ie 3.3.1.0) until a new series is released or one week has passed since the last revision was released. This is to protect the users from unstable versions.

You must provide a link to the Railcraft Blog, Railcraft Wiki and Railcraft License on your website.
Beta builds are never to be packaged as part of a public mod pack. Only public releases ending in zero (x.x.x.0) can be used in public mod packs.

Explicit permission is no longer required thanks to the great support via Patreon! Meet the above requirements and you are good.

Link: http://railcraft.info/wiki/info:license

**Comment by RyanTheAllmighty** [comment]
Thanks this has already been reported
