### ISSUE TITLE
Can't subscribe to any thread.

### ISSUE THREAD

**Issue by ShadedPL** [ATLauncher/Website-Issues#19]
Hello,
Recently I'm occurring a weird bug with not being able to subscribe to any thread I tried to subscribe to by clicking the "Subscribe to this thread" link. I'm getting:
"Authorization code mismatch. Are you accessing this function correctly? Please go back and try again."
Tried several times with no success. 
Cheers.

**Comment by RyanTheAllmighty** [comment]
Fixed, thanks for letting me know
