### ISSUE TITLE
Srv Records for server listings

### ISSUE THREAD

**Issue by tr0nlegacy2012** [ATLauncher/Website-Issues#21]
Hello,

My name is tyler, known as tr0nlegacy2012, and I am the owner of the tronopolis server network.

I would like to have srv Records enabled for my voting links if possible.

http://servers.atlauncher.com/server/TronopolisNetworkIPskytronopolisnetSkyFactory222LuckyBlocksandVeinminer

http://servers.atlauncher.com/server/TronopolisModSauce

**Comment by RyanTheAllmighty** [comment]
The main issue we have with SRV is we've never been able to reliably retrieve the records to properly do it. It's on the to do list to fix, but if you want it fixed on the site then you can contact us at http://www.atlauncher.com/contactus
