### ISSUE TITLE
Location change

### ISSUE THREAD

**Issue by mattymaats** [ATLauncher/Website-Issues#24]
Hi Ryan,

We've had to put in a few DDOS protection features for our network this week and since then our server is now showing up in Romania as that's where one of our proxies is based. Is there anyway to fix this manually so it's correct like before?

**Comment by RyanTheAllmighty** [comment]
Unfortunately not, the location is based on the ip/hostname provided and will auto reset itself. Allowing it to be changed will most likely lead to more people wanting it done and causing issues with fake locations to attract users away from exoctic/non local locations.

But contact us at http://www.atlauncher.com/contact-us and if you can provide the direct IP of the server that we can connect to and confirm it's all legit, then I will be happy to do an override.
