### ISSUE TITLE
Server Lists!

### ISSUE THREAD

**Issue by Gowps** [ATLauncher/Website-Issues#27]
Someone has listed my server in the server lists - http://servers.atlauncher.com/server/TheOfficialNetherBaneServer
I do not want my server listed as that, on your server lists, as i want to add it myself, under a different modpack, under a different name.
Thank you very much for your time
Gowps

**Comment by RyanTheAllmighty** [comment]
Hi,

Please use our contact form on our site to contact us about this issue

http://www.atlauncher.com/contact-us
