### ISSUE TITLE
Couple display issues (xml and changelog editors)

### ISSUE THREAD

**Issue by Cherry** [ATLauncher/Website-Issues#30]
The changelog editor for versions always says "add". That makes sense the first time, but "update" would make more sense if it's already set. I don't think it said "add" prior to the theme change, but could be wrong about that.

Additionally, the help text above the XML editor is identical to that of the configs upload window. "Here you can edit the configs associated with this version of the pack"...

Happy to provide further info if necessary.

**Comment by RyanTheAllmighty** [comment]
Yeah copy and past FTW. I'll pop a fix shortly

**Comment by RyanTheAllmighty** [comment]
Okay all fixed
