### ISSUE TITLE
Paid for Featured server 2 weeks Error

### ISSUE THREAD

**Issue by pallopoika** [ATLauncher/Website-Issues#31]
So i just paid for 2 weeks and money was taken but when i come back to the site it said oops error something? But money was taken from my card! and i just see 2 servers featured on the server list!

**Comment by RyanTheAllmighty** [comment]
Yes there was an issue at the time this occured. It's being investigated and all payments have either been refunded or applied to a featured slot

**Comment by pallopoika** [comment]
do i need to do something to get refund?? just checked paypal and nothing yet! because my server was not listed there in the 5 feautred slots?

**Comment by pallopoika** [comment]
or do i need to post the transaction id??

**Comment by RyanTheAllmighty** [comment]
You'd be best to send all the details including transaction ID through the contact form at http://www.atlauncher.com/contact-us

**Comment by pallopoika** [comment]
ok will do now!

**Comment by RyanTheAllmighty** [comment]
Alright I'll attend to your message shortly but this issue is closed now as I have hopefully fixed the backend issue which caused this to happen
