### ISSUE TITLE
Edit Link no longer working

### ISSUE THREAD

**Issue by devryb** [ATLauncher/Website-Issues#32]
Can you resend me the edit link for http://servers.atlauncher.com/server/DeVcoServers
The one I have seems to just bring up a blank page

**Comment by RyanTheAllmighty** [comment]
You need to use the contact us page on our website at http://www.atlauncher.com/contact-us/ to get the edit link resent to you.

As for the blank page, we're working on it

**Comment by RyanTheAllmighty** [comment]
Fixed
