### ISSUE TITLE
Server List uptime odd

### ISSUE THREAD

**Issue by devryb** [ATLauncher/Website-Issues#35]
I can say for a fact we've had 100% uptime today but this shows something different:

http://servers.atlauncher.com/server/DeVcoServers
http://puu.sh/gSi1D/c9f24b0765.jpg

**Comment by RyanTheAllmighty** [comment]
Yeah there is alot of variables which lead to bad reads for the uptime checks. We've recently rolled out changes to the system which we will be tweaking over the coming weeks which will mean constant resetting of the history on the site while we try to find the right balance.
