### ISSUE TITLE
Strange player counts

### ISSUE THREAD

**Issue by ThunderNetwork** [ATLauncher/Website-Issues#36]
http://servers.atlauncher.com/server/970

The motd has become the online players,
the online players is always 50/0,
it started happening when you updated your website..

Thanks for your time =D,
Regards

**Comment by RyanTheAllmighty** [comment]
Your server isn't returning correct data to our queries.

You're not sending a MOTD which is causing the issue. Are you using any custom software to run the server and change those queries or do you not have a MOTD set?

Either way I'll fix it and it should fix itself shortly, the issue should close once I've pushed the changes lice

**Comment by RyanTheAllmighty** [comment]
Alright this has been fixed. No MOTD will come up for your server anymore, not sure why it's not responding with it, I'll have to look into it later, but for now it shows the right player count

**Comment by ThunderNetwork** [comment]
ok thanks for you time =D it was running completely fine until i got the email saying you where changing a few things.. i havent changed anything in a while but its ok i can do without.

**Comment by RyanTheAllmighty** [comment]
Alright MOTD is back :)
