### ISSUE TITLE
Forge libraries tool doesn't work, returns empty error

### ISSUE THREAD

**Issue by D3add3d** [ATLauncher/Website-Issues#41]
The Forge libraries tool returns empty error and doesn't upload any libraries to provided folder.
![untitled-1](https://cloud.githubusercontent.com/assets/1764903/7441483/53150aa8-f0ea-11e4-8454-5fe19b20f63f.png)

UPDATE: It does not work with the 1710ls branch, it works fine with everything before

**Comment by RyanTheAllmighty** [comment]
Alright this should be fixed now
