### ISSUE TITLE
Voting Packets not Sent

### ISSUE THREAD

**Issue by LCAdmin** [ATLauncher/Website-Issues#42]
Seems as though the server listings are not sending voting packets again to servers. Uptime detector seems fine though this time. Vote count is also working.

**Comment by RyanTheAllmighty** [comment]
I'd need to know which server/s are being affected and permissions to debug this from the server owner (we may send alot of votifier packets to debug the issue).

So if you can send through that information to http://www.atlauncher.com/contact-us/ then I can take a look.
