### ISSUE TITLE
Votes goes down

### ISSUE THREAD

**Issue by brobon** [ATLauncher/Website-Issues#43]
Hey,
my issue is that the total votes going down from my server... 
https://servers.atlauncher.com/server/LycodonSkyFactoryVersion23

Yesterday I had 700. Today 669... Last week over 800...

Thanks ;)

**Comment by RyanTheAllmighty** [comment]
Votes over 2 weeks old are purged everyday in order to keep realistic numbers, else you'd see servers with hundreds of thousands of votes which wouldn't be realistic to obtain most likely.
