### ISSUE TITLE
Servers aren't recognised as being online on server listing site

### ISSUE THREAD

**Issue by Mickimoo2** [ATLauncher/Website-Issues#45]
Well basically I go to check where my servers are listed for both natural magic and modsauce and I see they have been offline for at least two days. I played around with my bungeecord settings and it didn't seem to change the problem at all. I spoke to Yive about the problem and from researching a bit about this it may be a problem from the site itself not from my backend.

IP:
ms.chillaid.org
nm.chillaid.org

Servers:
Chillaid Modsauce Server
Chillaid Natural Magic Server

**Comment by RyanTheAllmighty** [comment]
Can you provide the links to the listings on the site

**Comment by Mickimoo2** [comment]
https://servers.atlauncher.com/server/ChillaidModsauceServer
https://servers.atlauncher.com/server/ChillaidNaturalMagicServer

**Comment by RyanTheAllmighty** [comment]
The issue most likely stems from whatever version of bungiecord you're using not supporting 1.6 queries. We don't do 1.7 type queries, only 1.6 types to which I'd guess your bungiecord doesn't support

**Comment by Mickimoo2** [comment]
The bungeecord version I am running was provided by Yive as a fix to cauldron servers.

**Comment by RyanTheAllmighty** [comment]
Yeah I have no idea about bungeecord, never used it so I cannot confirm or deny what query version it uses. There may be an option that disables old queries, else it may just be removed entirely.

As I said we don't support 1.7 queries and may not for a while.

Also are you using SRV records? Both the domains have no SRV records and both point to the same IP and port so that may also be an issue maybe?

**Comment by Mickimoo2** [comment]
They both point to the bungeecordproxy which then recognises that they are different connecting ips so then it forces them to go to their specified server.

The main IP to join the server is play.chillaid.org. This sends them to the hub as well as any of the ips would by default. In the config I can specify a specific ip to go through to a specified server so people don't need to always go through the hub to get to the server they want as they can use 'direct connection'.

listeners:
- max_players: 100
  fallback_server: hub
  host: 0.0.0.0:25565
  bind_local_address: true
  ping_passthrough: false
  tab_list: SERVER
  default_server: hub
  forced_hosts:
    ms.chillaid.org: modsauce
    infinity.chillaid.org: infinity
    nm.chillaid.org: naturalmagic
    trident.chillaid.org: trident
  tab_size: 30
  force_default_server: true
  motd: '&6&k!&b&k!&6&k!&b&lChillaid&6 -&4Server&6-&b&l Network&6&k!&b&k!&6&k!&c Join Our Servers Today! &b-&a Servers: &9Modsauce, Natural Magic, FTB Infinity + Trident&a&3'
  query_enabled: true
  query_port: 25565

**Comment by RyanTheAllmighty** [comment]
Yeah no idea how bungee works :)

But yeah I don't think there's anything I can do to fix this at this point in time unfortunately.

I'll leave this issue open as a reminder as to the issue

**Comment by Mickimoo2** [comment]
Yive has built a version of bungeecord that addresses this issue and is reverted back to 1.6 queries.

https://tcpr.ca/files/fixes/BungeeCord.zip
