### ISSUE TITLE
When adding server, getting error: 'Cannon connect to the server!'

### ISSUE THREAD

**Issue by iCraftio** [ATLauncher/Website-Issues#51]
Title says it all. Thank you in advance!

[Picture](https://cloud.githubusercontent.com/assets/12716770/7939921/ef1f2eda-094d-11e5-91bb-c972acdb369d.png)

**Comment by Yorkforce** [comment]
We just started running into this problem too, it's awkward as the ip we have advertised is now for a server that's no longer available and can't we change it.

**Comment by RyanTheAllmighty** [comment]
It's possible I may have messed it up. Can you check now and see if it works?

**Comment by Yorkforce** [comment]
That worked, its saving properly now. Thanks Ryan! :)
