### ISSUE TITLE
SRV Record doesnt appear to be updating on listing.

### ISSUE THREAD

**Issue by Kyle2004uk** [ATLauncher/Website-Issues#52]
https://servers.atlauncher.com/server/1163

players can connect via rise.multicube.co

but listing still shows rise.multicube.co:25100

**Comment by RyanTheAllmighty** [comment]
We can connect fine to rise.multicube.co, what are you inputting into the host field? You should be inputting your SRV record of 'rise.multicube.co'

**Comment by tr0nlegacy2012** [comment]
He is referring to this: http://prntscr.com/7e569t

meanwhile his shows: http://prntscr.com/7e56qq

**Comment by RyanTheAllmighty** [comment]
I know this.

They have their host field incorrect and need to change it to their SRV record

**Comment by tr0nlegacy2012** [comment]
If his SRV record on his end was incorrect, why am I able to connect using rise.multicube.co when it is infact port 25100

**Comment by RyanTheAllmighty** [comment]
Never said the SRV record was incorrect. It's correct and we can connect to it. The host on our site needs to be changed by the creator of the listing.

**Comment by tr0nlegacy2012** [comment]
Are you meaning, the port should be left blank since the SRV record is enabled?

**Comment by RyanTheAllmighty** [comment]
SRV records don't require ports, that's the point of an SRV records, so yes, you'd need to enter your SRV record as the host.
