### ISSUE TITLE
Unable to feature server

### ISSUE THREAD

**Issue by Rob5Underscores** [ATLauncher/Website-Issues#53]
Attached image seen when trying to feature server.

Cheers
![screen shot 2015-06-13 at 18 11 45](https://cloud.githubusercontent.com/assets/5481153/8145253/72c8b51e-11f8-11e5-9534-de195e24e236.png)

**Comment by RyanTheAllmighty** [comment]
Do you have an EXACT time this occurred?

**Comment by Rob5Underscores** [comment]
Now and still current happening. First time at around 18:15pm GMT

**Comment by RyanTheAllmighty** [comment]
I see no errors popping up, I'll take a look into it and get back to you

**Comment by Rob5Underscores** [comment]
I just created a test server listing on ATL and tried to feature it, same error.

**Comment by Rob5Underscores** [comment]
Still not working.

**Comment by RyanTheAllmighty** [comment]
Should work again now hopefully once the system flushes out it's caches within the hour
