### ISSUE TITLE
ATLauncher only recording half of our votes.

### ISSUE THREAD

**Issue by Rob5Underscores** [ATLauncher/Website-Issues#54]
I have been watching the number of votes fall for my server over the last week or so (maybe more) despite the fact that our daily rate (calculated per-site per day) has risen. Upon further investigation it seems that only the first of every pair of votes is being counted.

It works as follows: the first vote will record then the next one won't, this repeats. Its strange as all votes still come through votifier as I am able to record them easily.

Would appreciate it if we could get this looked in to.

**Comment by RyanTheAllmighty** [comment]
Should be fixed once the system flushes out it's caches within the hour
