### ISSUE TITLE
Paid for 2 weeks featured, only got one.

### ISSUE THREAD

**Issue by Rob5Underscores** [ATLauncher/Website-Issues#56]
Another one, sorry Ryan!

http://i.imgur.com/fhIikoD.png

As the title suggests, paid for 2 weeks of server featured slot but the time duration only says 1?

**Comment by Rob5Underscores** [comment]
On second thoughts, is this because its like 1 week, 6 days, 23 hours, 59 mins or something?

**Comment by RyanTheAllmighty** [comment]
Indeed that is the case
