### ISSUE TITLE
Impossible to get advertising anymore.

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#57]
It is impossible to get server advertising anymore. It has been the same 5 advertisements for over a month. Why is this unfair? It limits smaller servers/networks ability to expand their own community. I've been trying to get advertising on the ATL serverlist for weeks now and it's nearly impossible because of these same networks most likely botting the server list. It's exremely annyoing to me and I'm sure many other people that these "large" networks can get server advertising in SECONDS??!?! Here's an article about how reCapatcha can be botted [[Link]](http://www.shieldsquare.com/sorry-google-captcha-recaptcha-doesnt-stop-bots/). Please do something about this as it is extremely unfair and annoying.
-Time

**Comment by RyanTheAllmighty** [comment]
Sorry but it's first come first serve.

Our solution will be to encourage bidding for slots as other lists do, but
we have chosen not to go that route.

Sorry you can't get a slot, but as I said, its first come first server.

**Comment by Time6628** [comment]
But it's not first come first serve, it's first bot first serve. :disappointed:

**Comment by RyanTheAllmighty** [comment]
Still counts as first come first serve regardless of bot, human, dog etc.

**Comment by Time6628** [comment]
Guess everyone should start breaking out their capatcha solvers. :/
