### ISSUE TITLE
Not sending votes.

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#60]
The serverlist does not appear to be sending the votes to the server.

**Comment by RyanTheAllmighty** [comment]
I'd need to know some more information such as times this is occuring (with timezone) and also the server on the list that's showing the issue

**Comment by Time6628** [comment]
All the time. [[Server Page]](https://servers.atlauncher.com/server/1157).

**Comment by RyanTheAllmighty** [comment]
I need to know specific times and timezones when it occurs else I cannot look it down to the precise reason in the log server

**Comment by RyanTheAllmighty** [comment]
I updated some server side software last night to which all votes stopped being sent so I'll get that fixed/reverted and post when resolved

**Comment by RyanTheAllmighty** [comment]
Have you been receiving any of the votes I've been sending to your server over the past hour?

**Comment by RyanTheAllmighty** [comment]
Okay this has been resolved now

**Comment by Time6628** [comment]
Can confirm it works now on all our servers. Thanks Ryan :smile_cat:
