### ISSUE TITLE
1.6.4 Servers cannot be connected to via serverlist?

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#61]
Trying to add my Fire In The Pipe server to the serverlist but it tells me it can not connect to the server.
Address: fitp.kookykraftmc.com 
Direct: 37.59.48.212:25566

**Comment by RyanTheAllmighty** [comment]
No issues here with our query server:

````
{
    "id": 970,
    "host": "fitp.kookykraftmc.com",
    "port": 25565,
    "online": true,
    "time_taken": 1587,
    "motd": "A Minecraft Server",
    "players": {
        "online": 0,
        "max": 50
    },
    "new_method": false
}
````

**Comment by Time6628** [comment]
port is 25566. And I still can't add it to the serverlist no matter what I put it in... lol

**Comment by RyanTheAllmighty** [comment]
Keeping the port as 25565 with the subdomain name, since it's a SRV record, will allow it to work.

Again the connection time is long so it may just take a few attempts for it to connect and not timeout possibly since we can see and query it

**Comment by Time6628** [comment]
Even 37.59.48.212:25565 doesn't work. I changed the port to 25565 and still get nothing. :crying_cat_face:

**Comment by RyanTheAllmighty** [comment]
I'll take a look, but as far as our system is concerned, it's a connectible address :\

**Comment by Time6628** [comment]
This happens when I try to edit my others servers as well.

**Comment by RyanTheAllmighty** [comment]
It's possible I may have messed it up. Can you check now and see if it works?

**Comment by Time6628** [comment]
Seems to be working now. Thanks man! :smile_cat:
