### ISSUE TITLE
Server Listing showing server as offline when its not

### ISSUE THREAD

**Issue by Yorkforce** [ATLauncher/Website-Issues#62]
I have noticed that our server listing for unioncraft is showing us as offline periodically when we are in fact fully online and available (we always are, except the other day when we had a 4 hour downtime). Unfortunately it seems to be affecting our uptime stats too which can have a large effect when new players are seeking a new community to join.

Any chance you could have a peek Ryan? :)

**Comment by RyanTheAllmighty** [comment]
Hi,

Unfortunately this is the best we can do at the current time.

We're always looking into how we can make it more accurate, but with needing to query the hundreds of servers we do and the limited hardware we have available to do it bundled with software hiccups such as bad routing momentarily, connection timeouts etc, what we've got at the moment is what we've got.

Like I said we're looking into it every now and then when we have the capacity to upgrade things.

**Comment by Yorkforce** [comment]
Ahh that's fair enough, I can understand that completely.
It does seem to be better these last couple of days however but thanks either way.

**Comment by Yorkforce** [comment]
Sorry to bring this back up but were really suffering over this, our uptime is now showing as 83% when we have in fact not been offline at all in the last 4 weeks.

It only seems to be affecting a small number of listings, kinda feels unfair other servers are getting their uptime and online status reported correctly while ours isn't. Isn't there anything you can do Ryan?
