### ISSUE TITLE
Feature Request: Extended Share Code API

### ISSUE THREAD

**Issue by Cherry** [ATLauncher/Website-Issues#63]
The currently provided API for share codes is great, but leaves a lot to be desired, especially for hosting companies. Whilst this request could technically be accomplished entirely externally (though not with any of the publicly available APIs), considering how you already have the XML parsing mechanisms internally setup, I feel this would make more sense as an addition to the already existing share code API.

Example of a share code API response existing today: ```https://api.atlauncher.com/v1/share-codes/WA1KDFvi```

Ideally, with this extended API, a much more useful object would be returned that would compare the share code to the already existing modpack's XML, and then provide a list containing the following:

- Which mods need to be download and to which folders, etc including nodecdn download links
- Any files that need to be unzipped or special action taken
- Links for forge/minecraft jar downloads to the root folder
- Anything else I've likely forgotten in the XML schema

Happy to provide any further information!

**Comment by RyanTheAllmighty** [comment]
Yeah I'll happily add this information to the PSP API. So if you don't have access, I suggest you get that access ASAP as I'll probably add this stuff in within the next 24 hours.

**Comment by RyanTheAllmighty** [comment]
Details can be accessed at http://wiki.atlauncher.com/api:psp:share-code

But keep in mind it won't go live on the system until the issue has been closed to signify that the changes have been deployed to production servers.

**Comment by RyanTheAllmighty** [comment]
Alright this is done now.

Please take this as very beta ATM. It seemed to work fine, but there may be some slip ups not accounted for so please let me know through a new issue, or on this one, if there are any issues.
