### ISSUE TITLE
Older listings showing as offline

### ISSUE THREAD

**Issue by Yorkforce** [ATLauncher/Website-Issues#65]
I did bring this issue #62 up before in another ticket but I now believe I know what's causing the problem (all credits to another server owner who helped me identify the issue!)  and thought I would create a new issue with the new info as this may help other listings which have the same problem, if that wasn't the right thing to do I do apologize as I was unable to reopen the old issue.

Server listings that were created quite a while ago (ours was added 8 months ago) seem to have a problem where they show as periodically offline and report back inaccurate uptime stats as a result.

New listings don't have the same problem.

To demonstrate, this is our old listing which has the periodically offline issue:
https://servers.atlauncher.com/server/UnionCraftCrundeeCraftModsauce2SkyFactory2

This is a new listing i created recently which has the exact same details/ip address etc etc
https://servers.atlauncher.com/server/UCStars

It might take a few tries but the old listing will show as offline at some point, at the same time, the newer listing will show as online and working correctly.

I hope this helps sort the problem out.

For reference, here are a bunch of other server listings that all share the same issue and are all quite old listings (and all show as online in the minecraft server select screen):
https://servers.atlauncher.com/server/ModRealmsNetworkCrundeeCraftSkyFactoryCrackPackProjectFluxModSauce2
https://servers.atlauncher.com/server/HydroXSkyFactory24247NoWhitelist
https://servers.atlauncher.com/server/PixelmonCraft
https://servers.atlauncher.com/server/LycodonSkyFactoryVersion24

**Comment by Yorkforce** [comment]
I think I understand your reply to the older issue now Ryan, I guess older listings are so far down the list that when ATLauncher does it 20 minute check by the time it reaches those older listings it's reaching its hardware limits?

Would a possible way to 'refresh' an active listing so its moved back to the top be a viable option perhaps? Maybe even a small payment to do that?

**Comment by RyanTheAllmighty** [comment]
What's odd is that the query process queries the listings in the order they were created, so if that were the case, I'd be more inclined to think that the older listings would have better uptime than the newer ones.

This is still something I'm looking into, I'm at the moment looking into containerizing our external processes, which includes the server querier, which will allow me to be running multiple query applications and hopefully drastically increase the accuracy of it.

By the way with your second newer server listing, it shows as offline 2 times during the day at the same time every day. Is this your server doing restarts? If so it seems to be getting reliable data on it.

**Comment by Yorkforce** [comment]
Hmm that is odd.
Yes the server is on a 12 hour restart schedule which matches up perfectly with the second listing.

And thanks for looking into it

**Comment by Rob5Underscores** [comment]
@RyanTheAllmighty did you manage to fix it?

Looks as if my first listing did its first accurate query!

<img width="1140" alt="screen shot 2015-09-05 at 20 18 54" src="https://cloud.githubusercontent.com/assets/5481153/9700870/9099bd36-540b-11e5-80f0-9edc1e7b59cb.png">

**Comment by Rob5Underscores** [comment]
Any advance on this issue? Still prevalent amongst listings.

Cheers.

**Comment by RyanTheAllmighty** [comment]
I've not looked into this yet. I will let you know on this issue once I have. It most likely won't get looked into for a long while if I'm being honest sorry.

**Comment by RyanTheAllmighty** [comment]
This should no longer be an issue at all. It's moved to a infinitely* scalable system using API Gateway and Lambda with AWS so it should scale with no issues and not be bottlenecked by the same issues we've had in the past.
