### ISSUE TITLE
Server showing offline and in wrong location due to DDOS protection

### ISSUE THREAD

**Issue by mattymaats** [ATLauncher/Website-Issues#69]
Hi,

I've spoken to Ryan previously as we used to have a modsauce server and I had an issue with our listing as it would show up as offline and in the location of the proxy. Would it be possible to resolve this again and what would you need me to send to you? I can send the required information via private message to Ryan once requested by him as for security reasons I cannot display the servers IP.

**Comment by RyanTheAllmighty** [comment]
Sure thing.

Just send through the details of the IP and everything through https://www.atlauncher.com/contact-us/ and ping me here once sent and I'll take care of it

**Comment by RyanTheAllmighty** [comment]
What's the location of the server @mattymaats

**Comment by mattymaats** [comment]
the Netherlands :)

**Comment by RyanTheAllmighty** [comment]
Al right that's been changed and should be all good now
