### ISSUE TITLE
PermissionsEX Issues with setting up server Forge

### ISSUE THREAD

**Issue by CrafterOfRealms** [ATLauncher/Website-Issues#78]
Hey guys i'm having trouble setting up my server i'm not accustomed to managing Modded servers and i have a problem with forge essentials essentials or Permissionsex anyway i can't get Essentials to work forge essentials works but the ranks don't i guess and i'm trying to use PermissionsEX for ranks they work and everything i've used those ranks that i created on other servers of mine but the prefixes won't show up for some reason can anyone assist me with that:
- Getting PermissionsEX Prefixes to show
- Getting proper Essentials or Forge Essentials if needed
I'm Also using KCauldron

**Comment by RyanTheAllmighty** [comment]
This is not support. Use the forums.

**Comment by CrafterOfRealms** [comment]
Ok sorry <3
