### ISSUE TITLE
Unable to add Pack, change email address

### ISSUE THREAD

**Issue by CobaltSparkz** [ATLauncher/Website-Issues#79]
Like the title says, I am unable to add what pack my server is using, and I cannot change the email from an old email address, it worked once on of of my listings, but not on the others.

**Comment by RyanTheAllmighty** [comment]
Alright I'll take a look. Can you provide your server ID/URL for our listings site (not the edit link, just the normal everyday users link)

**Comment by CobaltSparkz** [comment]
https://servers.atlauncher.com/server/MultiCubeUKNetworkResonantRiseMainline

**Comment by RyanTheAllmighty** [comment]
Cheers. Will take a look and update this issue with any updates

**Comment by CobaltSparkz** [comment]
Hi Ryan,

Still having the issue, any feedback?

**Comment by RyanTheAllmighty** [comment]
I'll most likely have a chance to look into this weekend after next.

If it's urgent please pop a message in at https://www.atlauncher.com/contact-us with the values to change it to and can get it changed manually

**Comment by CobaltSparkz** [comment]
Hey, Sorry for not following this up. Still having it on our listings =(

**Comment by RyanTheAllmighty** [comment]
Yeah I've still not had the time to look into yet. I'll stop making empty promises and just let you know by updating this issue when it's fixed.

**Comment by CobaltSparkz** [comment]
No worries - Not a major issue, just a minor inconvenience :) As and when!

**Comment by RyanTheAllmighty** [comment]
Hi.

Sorry for the delay on this, all is resolved in my tests, please let me know if you find it not to be the case.

Thanks
