### ISSUE TITLE
Server Listing issue

### ISSUE THREAD

**Issue by Acute-Apathy** [ATLauncher/Website-Issues#80]
I recently tried to list my server Cruesian Craft on the official At Launcher server list. When I finished it said it would send me a e-mail but it  never came. The IP is 209.182.104.92:25565. Please help I was planing to go premium. Thank you

Liam

**Comment by RyanTheAllmighty** [comment]
Please use our contact form at https://www.atlauncher.com/contact-us

**Comment by Acute-Apathy** [comment]
Alright I sent it
