### ISSUE TITLE
Featured Server Spots Instatnly gone

### ISSUE THREAD

**Issue by Acute-Apathy** [ATLauncher/Website-Issues#83]
So after reading A good amount of threads I started to worry about the featured serer slots instantly being bought. I really want to get some more player activity on my server, but it seems almost impossible due to the fact that featured server spots are taken almost instantly. Is there some new way like a bidding system to implement or was I misinformed and the spots are actually not taken as quickly as the threads say.

**Comment by RyanTheAllmighty** [comment]
Yeah the spots can go quite quickly unfortunately. We've randomised the timings a bit to make it a little less predictable.

We chose not to do a bidding system from the beginning and will stick to that.

But while we do have those premium slots, we don't guarantee that they'll ever be available. It's a first come first serve, well never make any guarantee that you can get them.
