### ISSUE TITLE
Add HSTS header to websites

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/Website-Issues#85]
All https sites should have a HSTS header

https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/

**Comment by jamierocks** [comment]
CloudFlare can do this for you, thats if you use CloudFlare of course :p

**Comment by RyanTheAllmighty** [comment]
Nah we don't, too many bad experiences in the past.

**Comment by RyanTheAllmighty** [comment]
Done on all ATLauncher sites using HTTPS
