### ISSUE TITLE
Sky Factory server suddenly STOPPED WORKING!!!

### ISSUE THREAD

**Issue by aimankassam** [ATLauncher/Website-Issues#86]
Until just this morning, I had a perfectly working sky factory server, but this morning, when i tried to launch it, it said "The state engine was in incorrect state SERVER_STARTING and forced into SERVER_STOPPED. Errors may have been discarded" I left the generated crash report as well PLZ HELP!!
[crash-2016-08-09_09.32.45-server.txt](https://github.com/ATLauncher/Website-Issues/files/409046/crash-2016-08-09_09.32.45-server.txt)

**Comment by RyanTheAllmighty** [comment]
Use the forums at https://forums.atlauncher.com for support
