### ISSUE TITLE
Cannot add a new server vote-site (no confirmation e-mail)

### ISSUE THREAD

**Issue by LameGirlyCurly** [ATLauncher/Website-Issues#89]
I've been trying to add a vote-site for two different packs:
https://www.atlauncher.com/pack/SpilledJuice (semi-public)
https://www.atlauncher.com/pack/SurvivalIndustry (public)

using two different e-mails (both gmail though).

Previously I've added several pages without any issues, now I get only the message about to look into the e-mail for confirmation. I can't submit any logs or such as I have none :) I'm happy to give details if needed.

**Comment by RyanTheAllmighty** [comment]
Can you either private message me on our discord https://atl.pw/discord or use our contact form at https://www.atlauncher.com/contact-us the emails you used to sign up as well as the ip/hosts of the servers

**Comment by RyanTheAllmighty** [comment]
Alright this is due to our email server API keys changing due to my error mistankingly deleting it.

Being fixed now, it should resend the emails in the queue and should come through within the next hour. If not, please let me know on this issue.
