### ISSUE TITLE
[Forum Issue] Remove the 7 banners on top

### ISSUE THREAD

**Issue by MrAmericanMike** [ATLauncher/Website-Issues#90]
How would I go about removing the 7 banners that show on top of the Forum.

They are really annoying covering the whole screen from the content that is really important. 

I'm talking about the ones with yellow and red backgrounds. It would be amazing if you can get rid of those.

Thanks a lot.

**Comment by RyanTheAllmighty** [comment]
They're there to prevent shitposting.

They'll be staying there for they moment, if you wish to get rid of it, I highly recommend you block the elements with an adblocker.
