### ISSUE TITLE
Voting not going through

### ISSUE THREAD

**Issue by Time6628** [ATLauncher/Website-Issues#95]
Votes are not coming through on the serverlist.
Tested with https://servers.atlauncher.com/server/1363 and the username Time6628 at 10:10PM EST.

**Comment by Tikas2** [comment]
Same here, tested on https://servers.atlauncher.com/server/ScrapsofLife with username Tikas2 at 8:11PM GMT+1 .

**Comment by Tikas2** [comment]
I would love a reply to this, its a pretty big deal! This is how players automaticly receive their Member status on our server and if this doesnt work there is no incentive to vote, meaning no new players...

Greets,
Tikas

**Comment by Time6628** [comment]
Ryan is dealing with personal things at the moment, please be patient. @Tikas2

**Comment by Tikas2** [comment]
Alrighty, thanks for the reply :+1:

**Comment by RyanTheAllmighty** [comment]
Yup I'm still investigating this. This issue will be updated when it's fixed

**Comment by RyanTheAllmighty** [comment]
Should be resolved now

**Comment by Tikas2** [comment]
Sure is, thanks Ryan! :D
