### ISSUE TITLE
Server edit/add page can't connect to server

### ISSUE THREAD

**Issue by LameGirlyCurly** [ATLauncher/Website-Issues#99]
My both efforts to either try and add a new fresh server and to edit the description of old existing one fail with the same error; "Cannot connect to the server!".

pack: Beyond Reality
ip: 138.201.134.44
port: 25560
whitelisted: yes

and the server I was trying to add:
pack: Resonant Rise
ip: 138.201.196.161
port: 25561
whitelisted yes:

Both I've tried with and without votifier. Bizzare enough, the BR server shows up as online at

https://servers.atlauncher.com/server/1482/

but editing that gives again the same error.

I've tried rebooting the hardware, no use.

**Comment by RyanTheAllmighty** [comment]
Issue should be fixed now and I've added in 2 days to your featured listing

**Comment by LameGirlyCurly** [comment]
Thank you, worked nicely.
